### ISSUE TITLE
Styles are note rendered in the apps/storybook-react-native/ app.

### ISSUE THREAD

**Issue by robincwillis** [dohomi/nativewind-solito-kitchen-sink#1]
I tried building/running [apps](https://github.com/dohomi/nativewind-solito-kitchen-sink/tree/master/apps)/storybook-react-native/ for ios

It runs fine but none of the components have any styles. I suspect some configuration needed between storybook, babel and nativewind is missing here.

**Comment by dohomi** [comment]
@robincwillis I only created this package as a demo, I moved using https://tamagui.dev/
